
package Login;

//import MODELO.frmVentanas;

import Busqueda.BuscarBoletaa;
import Busqueda.BuscarConductor;
import Busqueda.BuscarR_E_S;
import Busqueda.BuscarRuta;
import Busqueda.Buscarfrm;
import MODELO.Busesfrm1;
import MODELO.Conductoresfrm;
import MODELO.Entrada_Salidafrm;
import MODELO.Rutasfrm;
import MODELO.boletasfrm;
import MODELO.frmVentanas;
import Pasaje.Pasajes1;
import javax.swing.JOptionPane;
import solicitudes.Taller_Mecanico;
import solicitudes.buses2;

//Abre los PDF
import java.awt.Desktop;
import java.io.File;
import javax.swing.JOptionPane;
import otros.Papeletapuestas;
import otros.Papeletas;



public class Principalfrm extends javax.swing.JFrame {

    
    public Principalfrm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        DATOS = new javax.swing.JMenuItem();
        MENU = new javax.swing.JMenu();
        BUSES = new javax.swing.JMenuItem();
        CONDUCTORES = new javax.swing.JMenuItem();
        SALIDAS = new javax.swing.JMenuItem();
        RUTAS = new javax.swing.JMenuItem();
        BOLETAS = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        BUSESMODELO = new javax.swing.JMenuItem();
        MECANICOS = new javax.swing.JMenuItem();
        Otros = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        BUSES12 = new javax.swing.JMenuItem();
        CONDUCTORES12 = new javax.swing.JMenuItem();
        ENTRADA12 = new javax.swing.JMenuItem();
        RUTA12 = new javax.swing.JMenuItem();
        BOLETA12 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        CARGARPAPELETAS = new javax.swing.JMenuItem();
        BUSCARPAPELETAS = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        PASAJES = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        PDF = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        SALIR = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem10.setText("jMenuItem10");

        jMenuItem12.setText("jMenuItem12");

        jMenuItem13.setText("jMenuItem13");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PANTALLA DE INICIO DEL REGISTRO DE LOS BUSES POLLITOS ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel2.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\Bus.png")); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\Bus2.jpg")); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\Bus3.png")); // NOI18N

        jLabel6.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(67, 67, 67)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(96, 96, 96)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel3)
                            .addGap(26, 26, 26)
                            .addComponent(jLabel5))))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(232, Short.MAX_VALUE))
        );

        jMenu2.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\Clientes.png")); // NOI18N
        jMenu2.setText("INICIO");

        DATOS.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\Actualizar.png")); // NOI18N
        DATOS.setText("DATOS DE LOS BUSES");
        DATOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DATOSActionPerformed(evt);
            }
        });
        jMenu2.add(DATOS);

        MENU.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\torta.png")); // NOI18N
        MENU.setText("MENU");

        BUSES.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\enter.png")); // NOI18N
        BUSES.setText("Buses");
        BUSES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSESActionPerformed(evt);
            }
        });
        MENU.add(BUSES);

        CONDUCTORES.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\enter.png")); // NOI18N
        CONDUCTORES.setText("Conductores");
        CONDUCTORES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONDUCTORESActionPerformed(evt);
            }
        });
        MENU.add(CONDUCTORES);

        SALIDAS.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\enter.png")); // NOI18N
        SALIDAS.setText("Entradas/Salidas");
        SALIDAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIDASActionPerformed(evt);
            }
        });
        MENU.add(SALIDAS);

        RUTAS.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\enter.png")); // NOI18N
        RUTAS.setText("Rutas");
        RUTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RUTASActionPerformed(evt);
            }
        });
        MENU.add(RUTAS);

        BOLETAS.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\enter.png")); // NOI18N
        BOLETAS.setText("Boletas ");
        BOLETAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOLETASActionPerformed(evt);
            }
        });
        MENU.add(BOLETAS);

        jMenu2.add(MENU);

        jMenuBar1.add(jMenu2);

        jMenu5.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\vendedor.png")); // NOI18N
        jMenu5.setText("SOLICITUDES");

        BUSESMODELO.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\Carritocompras.png")); // NOI18N
        BUSESMODELO.setText("Buses");
        BUSESMODELO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSESMODELOActionPerformed(evt);
            }
        });
        jMenu5.add(BUSESMODELO);

        MECANICOS.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\logomanten.png")); // NOI18N
        MECANICOS.setText("Revisión tecnica");
        MECANICOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MECANICOSActionPerformed(evt);
            }
        });
        jMenu5.add(MECANICOS);

        Otros.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\opcreport.png")); // NOI18N
        Otros.setText("Otros");
        Otros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OtrosActionPerformed(evt);
            }
        });
        jMenu5.add(Otros);

        jMenuBar1.add(jMenu5);

        jMenu6.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\lupa.png")); // NOI18N
        jMenu6.setText("BUSQUEDA");

        BUSES12.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\Carritocompras.png")); // NOI18N
        BUSES12.setText("Buses");
        BUSES12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSES12ActionPerformed(evt);
            }
        });
        jMenu6.add(BUSES12);

        CONDUCTORES12.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\proveedor.png")); // NOI18N
        CONDUCTORES12.setText("Conductores");
        CONDUCTORES12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CONDUCTORES12ActionPerformed(evt);
            }
        });
        jMenu6.add(CONDUCTORES12);

        ENTRADA12.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\reportes.png")); // NOI18N
        ENTRADA12.setText("Entrada/salida");
        ENTRADA12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ENTRADA12ActionPerformed(evt);
            }
        });
        jMenu6.add(ENTRADA12);

        RUTA12.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\report.png")); // NOI18N
        RUTA12.setText("Ruta");
        RUTA12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RUTA12ActionPerformed(evt);
            }
        });
        jMenu6.add(RUTA12);

        BOLETA12.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\Hola libre.png")); // NOI18N
        BOLETA12.setText("Boleta");
        BOLETA12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOLETA12ActionPerformed(evt);
            }
        });
        jMenu6.add(BOLETA12);

        jMenuBar1.add(jMenu6);

        jMenu4.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\Papelera.png")); // NOI18N
        jMenu4.setText("PAPELETAS");

        CARGARPAPELETAS.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\nuevo.png")); // NOI18N
        CARGARPAPELETAS.setText("CARGAR PAPELTAS");
        CARGARPAPELETAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CARGARPAPELETASActionPerformed(evt);
            }
        });
        jMenu4.add(CARGARPAPELETAS);

        BUSCARPAPELETAS.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\lupa.png")); // NOI18N
        BUSCARPAPELETAS.setText("BUSCAR PAPELETAS");
        BUSCARPAPELETAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARPAPELETASActionPerformed(evt);
            }
        });
        jMenu4.add(BUSCARPAPELETAS);

        jMenuBar1.add(jMenu4);

        jMenu8.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\ticket.png")); // NOI18N
        jMenu8.setText("PASAJE");

        PASAJES.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\Nventa.png")); // NOI18N
        PASAJES.setText("PASAJE");
        PASAJES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASAJESActionPerformed(evt);
            }
        });
        jMenu8.add(PASAJES);

        jMenuBar1.add(jMenu8);

        jMenu3.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\Salir.jpg")); // NOI18N
        jMenu3.setText("OTROS");

        PDF.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\pdf.png")); // NOI18N
        PDF.setText("AYUDA");
        PDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDFActionPerformed(evt);
            }
        });
        jMenu3.add(PDF);

        jMenuBar1.add(jMenu3);

        jMenu7.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\salir_1.png")); // NOI18N
        jMenu7.setText("SALIR");

        SALIR.setIcon(new javax.swing.ImageIcon("F:\\CUARTO CICLO\\JAVA PROYECTO\\Imagenes\\salir.png")); // NOI18N
        SALIR.setText("Salir");
        SALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIRActionPerformed(evt);
            }
        });
        jMenu7.add(SALIR);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DATOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DATOSActionPerformed
        // TODO add your handling code here:
        frmVentanas abrir = new frmVentanas();
    abrir.setVisible(true);
    }//GEN-LAST:event_DATOSActionPerformed

    private void SALIDASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIDASActionPerformed
        // TODO add your handling code here:
        Entrada_Salidafrm abrir= new Entrada_Salidafrm ();
        abrir.setVisible(true);                      
    }//GEN-LAST:event_SALIDASActionPerformed

    private void BUSESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSESActionPerformed
        // TODO add your handling code here:
         Busesfrm1 abrir= new Busesfrm1 ();
        abrir.setVisible(true);
                              
    }//GEN-LAST:event_BUSESActionPerformed

    private void BOLETASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOLETASActionPerformed
        // TODO add your handling code here:
        boletasfrm abrir= new boletasfrm();
        abrir.setVisible(true);  
    }//GEN-LAST:event_BOLETASActionPerformed

    private void CONDUCTORESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONDUCTORESActionPerformed
        // TODO add your handling code here:
        Conductoresfrm abrir= new Conductoresfrm ();
        abrir.setVisible(true);                        
    }//GEN-LAST:event_CONDUCTORESActionPerformed

    private void RUTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RUTASActionPerformed
        // TODO add your handling code here:
        Rutasfrm abrir= new Rutasfrm ();
        abrir.setVisible(true);                      
    }//GEN-LAST:event_RUTASActionPerformed

    private void MECANICOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MECANICOSActionPerformed
        // TODO add your handling code here:
        Taller_Mecanico abrir= new Taller_Mecanico ();
        abrir.setVisible(true); 
    }//GEN-LAST:event_MECANICOSActionPerformed

    private void OtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OtrosActionPerformed
        // TODO add your handling code here:
//           abrir= new  ();
//        abrir.setVisible(true); 
    }//GEN-LAST:event_OtrosActionPerformed

    private void BUSESMODELOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSESMODELOActionPerformed
        // TODO add your handling code here:
          buses2 abrir= new buses2 ();
        abrir.setVisible(true); 
        
    }//GEN-LAST:event_BUSESMODELOActionPerformed

    private void SALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIRActionPerformed
        // TODO add your handling code here
    int respuesta = JOptionPane.showConfirmDialog(this, "¿Está seguro de que desea salir?", 
                                                  "Confirmar salida ", JOptionPane.YES_NO_OPTION);
    if (respuesta == JOptionPane.YES_OPTION) {
        System.exit(0); // Cierra la aplicación
}

        
    }//GEN-LAST:event_SALIRActionPerformed

    private void CARGARPAPELETASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CARGARPAPELETASActionPerformed
        // TODO add your handling code here:
         Papeletapuestas abrir= new Papeletapuestas ();
        abrir.setVisible(true);
    }//GEN-LAST:event_CARGARPAPELETASActionPerformed

    private void PDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDFActionPerformed
        // TODO add your handling code here:
        // Especificar la ruta completa del archivo PDF
    String rutaPDF = "F:\\CUARTO CICLO\\OTROS\\TT- TRABAJO-- 06\\TAREA.pdf"; // Cambia esto por la ruta real de tu PDF
    File archivoPDF = new File(rutaPDF);

    // Verificar si el archivo existe
    if (archivoPDF.exists()) {
        try {
            // Intentar abrir el archivo PDF con el visor predeterminado del sistema
            Desktop.getDesktop().open(archivoPDF);
        } catch (Exception e) {
            // Si ocurre algún error al intentar abrir el archivo
            JOptionPane.showMessageDialog(this, "Error al abrir el archivo PDF: " + e.getMessage());
        }
    } else {
        // Si el archivo no existe, mostrar un mensaje
        JOptionPane.showMessageDialog(this, "El archivo PDF no existe en la ruta especificada.");
    }
    }//GEN-LAST:event_PDFActionPerformed

    private void BUSES12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSES12ActionPerformed
        // TODO add your handling code here:
        Buscarfrm abrir= new Buscarfrm ();
        abrir.setVisible(true);
    }//GEN-LAST:event_BUSES12ActionPerformed

    private void RUTA12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RUTA12ActionPerformed
        // TODO add your handling code here: 
        BuscarRuta abrir= new BuscarRuta ();
        abrir.setVisible(true); 
        
    }//GEN-LAST:event_RUTA12ActionPerformed

    private void BOLETA12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOLETA12ActionPerformed
        // TODO add your handling code here:
         BuscarBoletaa abrir= new BuscarBoletaa ();
        abrir.setVisible(true); 
    }//GEN-LAST:event_BOLETA12ActionPerformed

    private void CONDUCTORES12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CONDUCTORES12ActionPerformed
        // TODO add your handling code here:
         BuscarConductor abrir= new BuscarConductor();
        abrir.setVisible(true); 
    }//GEN-LAST:event_CONDUCTORES12ActionPerformed

    private void ENTRADA12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ENTRADA12ActionPerformed
        // TODO add your handling code here:
         BuscarR_E_S abrir= new BuscarR_E_S ();
        abrir.setVisible(true); 
    }//GEN-LAST:event_ENTRADA12ActionPerformed

    private void BUSCARPAPELETASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARPAPELETASActionPerformed
        // TODO add your handling code here:
        Papeletas abrir= new Papeletas ();
        abrir.setVisible(true);
    }//GEN-LAST:event_BUSCARPAPELETASActionPerformed

    private void PASAJESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASAJESActionPerformed
        // TODO add your handling code here:
        Pasajes1 abrir= new Pasajes1 ();
        abrir.setVisible(true);
        
    }//GEN-LAST:event_PASAJESActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principalfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principalfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principalfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principalfrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principalfrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem BOLETA12;
    private javax.swing.JMenuItem BOLETAS;
    private javax.swing.JMenuItem BUSCARPAPELETAS;
    private javax.swing.JMenuItem BUSES;
    private javax.swing.JMenuItem BUSES12;
    private javax.swing.JMenuItem BUSESMODELO;
    private javax.swing.JMenuItem CARGARPAPELETAS;
    private javax.swing.JMenuItem CONDUCTORES;
    private javax.swing.JMenuItem CONDUCTORES12;
    private javax.swing.JMenuItem DATOS;
    private javax.swing.JMenuItem ENTRADA12;
    private javax.swing.JMenuItem MECANICOS;
    private javax.swing.JMenu MENU;
    private javax.swing.JMenuItem Otros;
    private javax.swing.JMenuItem PASAJES;
    private javax.swing.JMenuItem PDF;
    private javax.swing.JMenuItem RUTA12;
    private javax.swing.JMenuItem RUTAS;
    private javax.swing.JMenuItem SALIDAS;
    private javax.swing.JMenuItem SALIR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
